### ISSUE TITLE
eating food deletes my food yet does not increase the hunger bar. 

### ISSUE THREAD

**Issue by Elyas2024** [IzzelAliz/Arclight#1407]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-c47e085

### OS & Java versions

OS: Linux Ubuntu Server. Java: 21

### Plugins and Mods

```raw
mods:
- alternate-current 1.8.0
	- antixray 1.4.2+1.21
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- architectury 13.0.3
	- arclight 1.0.0-SNAPSHOT+c47e085
	- badpackets 0.8.1
	- balm-fabric 21.0.11
	   \-- kuma_api 21.0.4
	- c2me 0.2.0+alpha.11.106+1.21
	   |-- c2me-base 0.2.0+alpha.11.106+1.21
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.106+1.21
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.106+1.21
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.106+1.21
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.106+1.21
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.106+1.21
	   |-- c2me-notickvd 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-allocs 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-math 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.106+1.21
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.106+1.21
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.106+1.21
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.106+1.21
	   |-- c2me-server-utils 0.2.0+alpha.11.106+1.21
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.106+1.21
	   |-- c2me-threading-lighting 0.2.0+alpha.11.106+1.21
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.106+1.21
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- chunky 1.4.16
	- cloth-config 15.0.127
	   \-- cloth-basic-math 0.6.1
	- collective 7.70
	- deathbackup 3.3
	- disableportalchecks 1.0.0
	- expanded_armor_enchanting 1.0.8
	- expanded_axe_enchanting 1.0.9
	- expanded_trident_enchanting 1.0.9
	- expanded_weapon_enchanting 1.0.8
	- fabric-api 0.100.4+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.28+6fc22b99d1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.48+f71b366fd1
	   |-- fabric-command-api-v2 2.2.27+6a6dfa19d1
	   |-- fabric-commands-v0 0.2.65+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.14+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.15+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.3.2+78017270d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.9+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.52+6573ed8cd1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.2+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.11+6573ed8cd1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.12+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.23+78017270d1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.70+df3654b3d1
	   |-- fabric-rendering-v1 5.0.4+5a8c785ed1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.1.5+78017270d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.80+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- fast-rtp 1.5.1-1.21
	   \-- fabric-permissions-api-v0 0.3.1
	- ferritecore 7.0.0
	- floodgate 2.2.3-SNAPSHOT
	   |-- aopalliance_aopalliance 1.0
	   |-- cloud 2.0.0-SNAPSHOT
	   |    |-- fabric-permissions-api-v0 0.3.1
	   |    |-- io_leangen_geantyref_geantyref 1.3.15
	   |    |-- org_incendo_cloud-brigadier 2.0.0-beta.8
	   |    |-- org_incendo_cloud-core 2.0.0-rc.2
	   |    |-- org_incendo_cloud-minecraft-modded-common-fabric-repack_ 2.0.0-SNAPSHOT
	   |    \-- org_incendo_cloud-services 2.0.0-rc.2
	   |-- jakarta_inject_jakarta_inject-api 2.0.1
	   |-- javax_inject_javax_inject 1
	   |-- org_geysermc_cumulus_cumulus 1.1.2
	   |-- org_geysermc_event_events 1.1-SNAPSHOT
	   |-- org_geysermc_geyser_common 2.2.3-SNAPSHOT
	   |-- org_java-websocket_java-websocket 1.5.2
	   \-- org_lanternpowered_lmbda 2.0.0
	- geyser-fabric 2.4.0-SNAPSHOT
	   |-- com_fasterxml_jackson_core_jackson-annotations 2.17.0
	   |-- com_fasterxml_jackson_core_jackson-core 2.17.0
	   |-- com_fasterxml_jackson_core_jackson-databind 2.17.0
	   |-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.17.0
	   |-- com_nukkitx_natives 1.0.3
	   |-- io_airlift_aircompressor 0.25
	   |-- io_netty_netty-codec-dns 4.1.107
	   |-- io_netty_netty-codec-haproxy 4.1.107
	   |-- io_netty_netty-resolver-dns-classes-macos 4.1.107
	   |-- net_bytebuddy_byte-buddy 1.14.9
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_kyori_adventure-nbt 4.15.0
	   |-- net_kyori_adventure-text-serializer-json-legacy-impl 4.15.0
	   |-- net_kyori_adventure-text-serializer-legacy 4.15.0
	   |-- net_kyori_examination-api 1.3.0
	   |-- net_kyori_examination-string 1.3.0
	   |-- net_kyori_option 1.0.0
	   |-- org_bitbucket_b_c_jose4j 0.9.3
	   |-- org_cloudburstmc_math_api 2.0
	   |-- org_cloudburstmc_math_immutable 2.0
	   |-- org_cloudburstmc_nbt 3.0.3
	   |-- org_geysermc_api_base-api 1.0.0-SNAPSHOT
	   |-- org_geysermc_cumulus_cumulus 1.1.2
	   |-- org_geysermc_event_events 1.1-SNAPSHOT
	   |-- org_lanternpowered_lmbda 2.0.0
	   \-- org_yaml_snakeyaml 2.2
	- glore 1.3.0
	- grindenchantments 3.2.2+1.21-rc1
	   \-- codec-config-api 2.0.0+1.20.5-rc3
	- hurricane 2.0.0
	   |-- com_typesafe_config 1.4.2
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- jamlib 1.0.9+1.21
	   \-- blue_endless_jankson 1.2.3
	- java 21
	- krypton 0.2.8
	   \-- com_velocitypowered_velocity-native 3.3.0-SNAPSHOT
	- ksyxis 1.3.2
	- letmedespawn 1.3.0
	- minecraft 1.21
	- minimotd-fabric 2.1.2
	   \-- adventure-platform-fabric 5.14.0
	        |-- net_kyori_adventure-api 4.17.0
	        |-- net_kyori_adventure-key 4.17.0
	        |-- net_kyori_adventure-platform-api 4.3.3
	        |-- net_kyori_adventure-text-logger-slf4j 4.17.0
	        |-- net_kyori_adventure-text-minimessage 4.17.0
	        |-- net_kyori_adventure-text-serializer-ansi 4.17.0
	        |-- net_kyori_adventure-text-serializer-gson 4.17.0
	        |-- net_kyori_adventure-text-serializer-json 4.17.0
	        |-- net_kyori_adventure-text-serializer-plain 4.17.0
	        |-- net_kyori_ansi 1.0.3
	        |-- net_kyori_examination-api 1.3.0
	        |-- net_kyori_examination-string 1.3.0
	        \-- net_kyori_option 1.0.0
	- modernfix 5.18.5+mc1.21
	- moretools 1.5.0+1.21
	- mr_clifftree 1.4
	- mru 0.4.4+1.21
	   \-- yet_another_config_lib_v3 3.5.0+1.21-fabric
	        |-- com_twelvemonkeys_common_common-image 3.10.0
	        |-- com_twelvemonkeys_common_common-io 3.10.0
	        |-- com_twelvemonkeys_common_common-lang 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- netherportalfix 21.0.2
	- nofeathertrample 1.2
	- noincreasingrepaircost 1.0.0
	- noisium 2.2.1+mc1.21
	   \-- mixinextras 0.3.5
	- passiveendermen 4.7
	- patched 7.0.0+1.21
	- perfectaccuracy 1.3
	- polymer-bundled 0.9.2+1.21
	   |-- polymer-autohost 0.9.2+1.21
	   |    \-- io_netty_netty-codec-http 4.1.82
	   |-- polymer-blocks 0.9.2+1.21
	   |-- polymer-common 0.9.2+1.21
	   |    \-- packet_tweaker 0.5.4+1.20.6
	   |-- polymer-core 0.9.2+1.21
	   |    |-- polymer-networking 0.9.2+1.21
	   |    |    \-- polymer-common 0.9.2+1.21
	   |    |         \-- packet_tweaker 0.5.4+1.20.6
	   |    \-- polymer-registry-sync-manipulator 0.9.2+1.21
	   |-- polymer-resource-pack 0.9.2+1.21
	   |    \-- polymer-common 0.9.2+1.21
	   |         \-- packet_tweaker 0.5.4+1.20.6
	   \-- polymer-virtual-entity 0.9.2+1.21
	        \-- polymer-common 0.9.2+1.21
	             \-- packet_tweaker 0.5.4+1.20.6
	- quickcurefabricrewrite 1.0.1-1.21
	- regsyncfix 1.0.1
	- rightclickharvest 4.3.1+1.21
	- silk-all 1.10.7
	   |-- silk-commands 1.10.7
	   |-- silk-core 1.10.7
	   |-- silk-game 1.10.7
	   |-- silk-igui 1.10.7
	   |-- silk-nbt 1.10.7
	   |-- silk-network 1.10.7
	   \-- silk-persistence 1.10.7
	- sneakyserver 1.0.13
	- snowundertrees 2.4.0+1.21
	   \-- yet_another_config_lib_v3 3.5.0+1.21-fabric
	        |-- com_twelvemonkeys_common_common-image 3.10.0
	        |-- com_twelvemonkeys_common_common-io 3.10.0
	        |-- com_twelvemonkeys_common_common-lang 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- spark 1.10.73
	   \-- fabric-permissions-api-v0 0.3.1
	- styledplayerlist 3.5.1+1.21
	   |-- fabric-permissions-api-v0 0.3.1
	   |-- placeholder-api 2.4.0+1.21
	   \-- player-data-api 0.6.0+1.21
	- tectonic 2.4.0
	- televator 1.1.7+1.21
	   |-- polymer-autohost 0.9.2+1.21
	   |    \-- io_netty_netty-codec-http 4.1.82
	   |-- polymer-blocks 0.9.2+1.21
	   |-- polymer-core 0.9.2+1.21
	   |    |-- polymer-networking 0.9.2+1.21
	   |    |    \-- polymer-common 0.9.2+1.21
	   |    |         \-- packet_tweaker 0.5.4+1.20.6
	   |    \-- polymer-registry-sync-manipulator 0.9.2+1.21
	   |-- polymer-resource-pack 0.9.2+1.21
	   |    \-- polymer-common 0.9.2+1.21
	   |         \-- packet_tweaker 0.5.4+1.20.6
	   \-- server_translations_api 2.3.1+1.21-pre2
	- transcendingtrident 4.7
	- twerk4fabric 1.0.0
	- universal-graves 3.4.1+1.21
	   |-- common-protection-api 1.0.0
	   |-- polymer-core 0.9.2+1.21
	   |    |-- polymer-networking 0.9.2+1.21
	   |    |    \-- polymer-common 0.9.2+1.21
	   |    |         \-- packet_tweaker 0.5.4+1.20.6
	   |    \-- polymer-registry-sync-manipulator 0.9.2+1.21
	   |-- polymer-resource-pack 0.9.2+1.21
	   |    \-- polymer-common 0.9.2+1.21
	   |         \-- packet_tweaker 0.5.4+1.20.6
	   |-- polymer-virtual-entity 0.9.2+1.21
	   |    \-- polymer-common 0.9.2+1.21
	   |         \-- packet_tweaker 0.5.4+1.20.6
	   |-- predicate-api 0.5.1+1.21
	   |-- server_translations_api 2.3.1+1.21-pre2
	   \-- sgui 1.6.0+1.21
	- unsaddle 0.2.1
	   |-- unsaddle-compat-1-15 0.2.1
	   |-- unsaddle-compat-1-16 0.2.1
	   \-- unsaddle-core 0.2.1
	- viewdistancefix 1.21-1.0.2
	- zombify 0.1.4

plugins:
Simple TPA
```

### Description

when i eat since my hunger is getting low, my food disapears but my hunger does not go up. it should increase my hunger not delete my food

### Step to reproduce

join the server
get ur hunger low
eat

### Logs

https://paste.sparked.host/bepopokote

**Comment by Elyas2024** [comment]
eating a cake is the exetption to this bug for some reason

**Comment by archeruwu** [comment]
Exact same issue here, cake is the only food that increases the hunger bar

**Comment by Twennyseeks** [comment]
Can confirm, cake is the only exception, no other food item works.

**Comment by qyl27** [comment]
Fixed, please refer #1469

**Comment by Fahin-A** [comment]
That's a terrible way to call it fixed.

**Comment by qyl27** [comment]
> That's a terrible way to call it fixed.

What do you want to say? Or just spamming?

**Comment by EmreKumas** [comment]
As of today, I can confirm the issue is still persisting. Nothing increases the hunger bar except the cake as mentioned. Sorry but its not fixed
