### ISSUE TITLE
[arclight-fabric-1.21.1] Multiverse-Core / PlotSquared 插件自定义世界功能异常

### ISSUE THREAD

**Issue by HikaQ** [IzzelAliz/Arclight#1641]
### 请确认您已完成以下几件事

- [x] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [x] 不可在 Spigot 复现
- [x] 不可在 Forge 复现

### Arclight 版本

arclight-fabric-1.21.1-1.0.0-SNAPSHOT

### Java 版本 | 操作系统

window 10 ; java version "21.0.3" 2024-04-16 LTS

### 相关 Mod/插件 的名称及版本

```raw
PlotSquared
Multiverse-Core
WorldEdit
```

### 错误描述

没有任何模组且仅有上述三种插件（最新版本），多世界插件功能在该核心运行异常
每当创建一个世界，所创建的任何世界都是同一种子，且PlotSquared无法正常被多世界插件使用，即使是创建成功后也是非正常的地皮世界。
p auto占领地皮后，服务端日志也会出现worldedit的异常

### 复现步骤

1. 安装 PlotSquared、Multiverse-Core、WorldEdit插件
2. 输入mv create test1 normal
3. 输入mv create test2 normal
4. 输入mv create test3 normal -g PlotSquared
5. 输入p auto
创建的三个世界种子均相同，地形均相同，无法正常生成PlotSquared地形

### 报错信息

[debug.log](https://github.com/user-attachments/files/18629408/debug.log)
[latest.log](https://github.com/user-attachments/files/18629409/latest.log)

**Comment by HikaQ** [comment]
感谢

**Comment by zwh113037371** [comment]
> 感谢

你找到有什么插件平替了吗 没地皮难受死我了

**Comment by HikaQ** [comment]
> > 感谢
> 
> 你找到有什么插件平替了吗 没地皮难受死我了

我服暂时阉割掉了，没有去找相关平替

**Comment by zwh113037371** [comment]
> > > 感谢
> > 
> > 
> > 你找到有什么插件平替了吗 没地皮难受死我了
> 
> 我服暂时阉割掉了，没有去找相关平替

别找了 我试了所有跟地形生成有关的插件都不正常。

**Comment by InitAuther97** [comment]
Can confirm in latest build.
[#1689: mv import doesn't work](https://github.com/IzzelAliz/Arclight/issues/1689#issuecomment-2692902714)

**Comment by InitAuther97** [comment]
PlotSquared doesn't work since it depends on WorldEdit, which is by default disabled. See [here](https://wiki.izzel.io/s/arclight-docs/doc/troubleshooting-1Ay2vsmIrn#h-worldedit-editing-on-unsupported-versions-is-disabled) for more detail; the world generating issue should be fixed in 6d22adf, please test it.

**Comment by zwh113037371** [comment]
> PlotSquared 不起作用，因为它依赖于 WorldEdit，而 WorldEdit 默认处于禁用状态。有关更多详细信息，请参阅[此处](https://wiki.izzel.io/s/arclight-docs/doc/troubleshooting-1Ay2vsmIrn#h-worldedit-editing-on-unsupported-versions-is-disabled);世界生成问题应该在 [6D22ADF](https://github.com/IzzelAliz/Arclight/commit/6d22adf422d0cd2c20c4323e0fea536db1e3c701) 中修复，请测试一下。

使用了最新的build，已经根据wiki修改了worldedit。WorldEdit功能正常，PlotSquared插件功能也正常。但世界生成问题依旧存在，生成出来的世界不正常。

**Comment by Flashback083** [comment]
I confirm that i think the world generation bug is still here (tried to create a new void world, it seems the seed is different but its not a void at all)
Edit : i tested the arclight build : 6d22adf

**Comment by InitAuther97** [comment]
Please test in InitAuther97/216e5ec

**Comment by InitAuther97** [comment]
Please try 1e03493

**Comment by Flashback083** [comment]
Might be wrong but i have still an issue with the build c1a58a9
the world is created, it seems its a new seed, but add a flat or void generator dont work
(Using MultiWorld for my test)

**Comment by InitAuther97** [comment]
> Might be wrong but i have still an issue with the build [c1a58a9](https://github.com/IzzelAliz/Arclight/commit/c1a58a92f8caeda6f44aacee0480130b05d6b321) the world is created, it seems its a new seed, but add a flat or void generator dont work (Using MultiWorld for my test)

These supports are a little bit experimental and are made available from my fork. The baseline I use now for my support is PlotSquared. Other plugin support may need to wait until I finish. Currently the world generator can be set later for a normal world (which is displayed as null>>PlotSquared in Console), but some WE schematic related functionality isn't available yet since it requires full WorldEdit support, which is now working in progress. So please be patient :)

**Comment by InitAuther97** [comment]
Plot world generation with WE schematic is supported, shipped with experimental full support of WorldEdit.
Please test the build result from here.
Remember to delete .arclight/class_cache on the first run.
https://github.com/InitAuther97/Arclight/actions/runs/13758135205

**Comment by HikaQ** [comment]
感谢，牛逼！可以正常使用了！！

**Comment by Flashback083** [comment]
Hey, so i did more tests somes days ago and its very weird (about Multiverse world generation issue)
I was able at one moment to create a void world twice with the [VoidGen ](https://www.spigotmc.org/resources/voidgen.25391/) plugin, with the following command : 

> /mv create void2 normal -g VoidGen -t FLAT
/mvtp void2
/mvconfirm (it ask for confirmation cause player will fall, its a good sign it worked)

So 2 times the world was created as the void  like intented
And after that every world i created in the SAME way, it created only a FLAT world, like if the plugin isnt reconized anymore or idk :( 
I'm sorry i didn't find yet how to reproduce that

**Comment by Jasaxion** [comment]
> Plot world generation with WE schematic is supported, shipped with experimental full support of WorldEdit. Please test the build result from here. Remember to delete .arclight/class_cache on the first run. https://github.com/InitAuther97/Arclight/actions/runs/13758135205

Please could you also apply the same modification to 1.20.1 Trials? The same error occurs when PlotSquared, Multiverse-Core, and WorldEdit are all installed together, and I believe the solution should be the same.

**Comment by InitAuther97** [comment]
> Hey, so i did more tests somes days ago and its very weird (about Multiverse world generation issue) I was able at one moment to create a void world twice with the [VoidGen ](https://www.spigotmc.org/resources/voidgen.25391/) plugin, with the following command :
> 
> > /mv create void2 normal -g VoidGen -t FLAT
> > /mvtp void2
> > /mvconfirm (it ask for confirmation cause player will fall, its a good sign it worked)
> 
> So 2 times the world was created as the void like intented And after that every world i created in the SAME way, it created only a FLAT world, like if the plugin isnt reconized anymore or idk :( I'm sorry i didn't find yet how to reproduce that

I will try to reproduce that

**Comment by InitAuther97** [comment]
> > Plot world generation with WE schematic is supported, shipped with experimental full support of WorldEdit. Please test the build result from here. Remember to delete .arclight/class_cache on the first run. https://github.com/InitAuther97/Arclight/actions/runs/13758135205
> 
> Please could you also apply the same modification to 1.20.1 Trials? The same error occurs when PlotSquared, Multiverse-Core, and WorldEdit are all installed together, and I believe the solution should be the same.

OK it'll be planned after this is stable and merged

**Comment by Jasaxion** [comment]
> > > Plot world generation with WE schematic is supported, shipped with experimental full support of WorldEdit. Please test the build result from here. Remember to delete .arclight/class_cache on the first run. https://github.com/InitAuther97/Arclight/actions/runs/13758135205
> > 
> > 
> > Please could you also apply the same modification to 1.20.1 Trials? The same error occurs when PlotSquared, Multiverse-Core, and WorldEdit are all installed together, and I believe the solution should be the same.
> 
> OK it'll be planned after this is stable and merged

Thank you very much for your patient maintenance. The following two issues (PlotSquared + Multiverse-Core) are problems that exist in the Trials version but have not been fixed. You may refer to them if needed. Once again, I sincerely appreciate your patience in maintaining the project and look forward to the stable version being released soon.

https://github.com/IzzelAliz/Arclight/issues/1299
https://github.com/IzzelAliz/Arclight/issues/1294

https://github.com/IzzelAliz/Arclight/issues/1455 （This is with TerraPlusMinus mod installed, but the error messages look very similar)

**Comment by AgentMelinda** [comment]
> > > > Plot world generation with WE schematic is supported, shipped with experimental full support of WorldEdit. Please test the build result from here. Remember to delete .arclight/class_cache on the first run. https://github.com/InitAuther97/Arclight/actions/runs/13758135205
> > > 
> > > 
> > > Please could you also apply the same modification to 1.20.1 Trials? The same error occurs when PlotSquared, Multiverse-Core, and WorldEdit are all installed together, and I believe the solution should be the same.
> > 
> > 
> > OK it'll be planned after this is stable and merged
> 
> Thank you very much for your patient maintenance. The following two issues (PlotSquared + Multiverse-Core) are problems that exist in the Trials version but have not been fixed. You may refer to them if needed. Once again, I sincerely appreciate your patience in maintaining the project and look forward to the stable version being released soon.
> 
> [#1299](https://github.com/IzzelAliz/Arclight/issues/1299) [#1294](https://github.com/IzzelAliz/Arclight/issues/1294)
> 
> [#1455](https://github.com/IzzelAliz/Arclight/issues/1455) （This is with TerraPlusMinus mod installed, but the error messages look very similar)

I'm the owner of #1455 
Terraplusminus is just a generation plugin
The problem is probably at how arclight handles bukkit custom generation plugin aka terraplusminus
Both plotsquard and multiworld and multiverse plugins are a custom bukkit world generator probably like we have mods of generation for forge 
This is the counterpart of bukkit
@InitAuther97 maybe the way arclight implant world bridge of bukkit and stuff is not fully implemented ?
